# Programmers Palettes
palettes for programmers, developers, and designers.

<https://github.com/paulwratt/programmers-palettes>

* NOTE: only a complete _set_ is released, which may mean manually creating some files, or at least manual tweeking of 
the root .html file, with the addition of NOTES or linking example graphics.

* NOTE: only I (paulwratt) will make commits to ./docs/index.html once a _set_ has been verified, as that also requires a date tagged version release.

----

* NOTE: at the moment (2017-09-11) all .html files need to be generated by hand (see example list at bottom).

# Update a Set

To update an individual file in a _set_ a folder called ./docs/_set_ containing _set_.gpl is required.  All filenames are generated from the folder name, not the .gpl name:

* cd ./docs/_set_/
* ../../bin/update-gpl2grafx2.pal.sh _set_.gpl
* ../../bin/update-gpl2paint.net.sh _set_.gpl

----

# Generate a Set

To generate a _set_ a folder called ./docs/_set_ containing _set_.gpl is required.  All filenames are generated from the folder name, not the .gpl name:

* cd ./docs/_set_/
* ../../bin/gpl2dec24-all-txt _set_.gpl
* ../../bin/gpl2hex24-all-txt _set_.gpl
* ../../bin/gpl2names-all-txt _set_.gpl
* ls -1
    * HW-CGA-dec-24-comma-space.txt
    * HW-CGA-dec-24-comma.txt
    * HW-CGA-dec-24-space-comma.txt
    * HW-CGA-dec-24-space.lst
    * HW-CGA-dec-24-space.txt
    * HW-CGA.gpl
    * HW-CGA.grafx2-JASC.pal
    * HW-CGA-hex-24-html.txt
    * HW-CGA-hex-24-space.txt
    * HW-CGA-hex-24.txt
    * HW-CGA-names-Caps-space.txt
    * HW-CGA-names-CAPS_.txt
    * HW-CGA-names-CAPS.txt
    * HW-CGA-names-cCaps.txt
    * HW-CGA-names-lower_.txt
    * HW-CGA-names.lst
    * HW-CGA-names-official.txt
    * HW-CGA.paint.net.txt

----

# Current _set_ files (example):

* ./docs/HW-MSX/
    * HW-MSX.html
    * HW-MSX-names.html
        * HW-MSX-C-names-array-official.h
        * HW-MSX-names-Caps.txt
        * HW-MSX-names-CAPS_.txt
        * HW-MSX-names-CAPS.txt
        * HW-MSX-names-cCaps.txt
        * HW-MSX-names-lower_.txt
        * HW-MSX-names-official.txt
    * HW-MSX-decimal.html
        * HW-MSX-C-colors24-array-dec.h
        * HW-MSX-C-colors32-array-dec.h
        * HW-MSX-dec-24-RGB-comma-space.txt
        * HW-MSX-dec-24-RGB-comma.txt
        * HW-MSX-dec-24-RGB-semi-colon.txt
    * HW-MSX-hex.html
        * HW-MSX-C-cCOLOR24-printf-hex.h
        * HW-MSX-C-cCOLOR32-printf-hex.h
        * HW-MSX-hex-24-BGR-printf.txt
        * HW-MSX-hex-24-RGB-forward-slash.txt
        * HW-MSX-hex-24-RGB-html.txt
        * HW-MSX-hex-24-RGB-printf.txt
        * HW-MSX-hex-24.txt
        * HW-MSX-hex-32-BGRA-printf.txt
        * HW-MSX-hex-32-RGBA-printf.txt
    * HW-MSX-palettes.html
        * HW-MSX.gpl (GiMP)
        * HW-MSX.grafix2.pal (JASC-PAL)
        * HW-MSX.paint.net.txt (Paint.Net)
        * HW-MSX-fbterm-24-RGB-t_COLORS-printf.sh
        * HW-MSX-xterm-24-RGB-t_COLORS-printf.sh

[denilsonsa]: https://github.com/denilsonsa
[gimp-preview]: http://denilsonsa.github.io/gimp-palettes/index.html
