#!/bin/sh
# generated by:
#  programmers-palettes
#  txt2xterm.colors.sh
#  https://github.com/paulwratt/programmers-palettes/tree/master/bin

if echo "$TERM" | grep "xterm" > /dev/null; then
    # CGA 16 color palette
    t_SETCOLOR='\033]4;%d;rgb:%s';  # for printf
    # xterm-color256: xterm screen rxvt urxtv gnome lxterminal tmux
    # xterm uses hexidecimal values in tput/ESC codes for 256 colors
    t_COLOR0="00/00/00";        t_BLACK="00/00/00";
    t_COLOR1="00/00/AA";        t_LOW_BLUE="00/00/AA";
    t_COLOR2="00/AA/00";        t_LOW_GREEN="00/AA/00";
    t_COLOR3="00/AA/AA";        t_LOW_CYAN="00/AA/AA";
    t_COLOR4="AA/00/00";        t_LOW_RED="AA/00/00";
    t_COLOR5="AA/00/AA";        t_LOW_MAGENTA="AA/00/AA";
    t_COLOR6="AA/55/00";        t_BROWN="AA/55/00";
    t_COLOR7="AA/AA/AA";        t_LIGHT_GRAY="AA/AA/AA";
    t_COLOR8="55/55/55";        t_DARK_GRAY="55/55/55";
    t_COLOR9="55/55/FF";        t_HIGH_BLUE="55/55/FF";
    t_COLOR10="55/FF/55";       t_HIGH_GREEN="55/FF/55";
    t_COLOR11="55/FF/FF";       t_HIGH_CYAN="55/FF/FF";
    t_COLOR12="FF/55/55";       t_HIGH_RED="FF/55/55";
    t_COLOR13="FF/55/FF";       t_HIGH_MAGENTA="FF/55/FF";
    t_COLOR14="FF/FF/55";       t_YELLOW="FF/FF/55";
    t_COLOR15="FF/FF/FF";       t_WHITE="FF/FF/FF";
fi
