#!/bin/sh
# generated by:
#  programmers-palettes
#  txt2fbterm.colors.sh
#  https://github.com/paulwratt/programmers-palettes/tree/master/bin

if echo "$TERM" | grep "fbterm" > /dev/null; then
    t_SETCOLOR='\033[3;%d;%s}';  # for printf
    # fbterm uses decimal values in tput/ESC codes for 256 colors
    # COLOR 0 is the transparencey (background image) color
    t_COLOR0="0;0;0";           t_BLACK="0;0;0";
    t_COLOR1="0;0;170";         t_LOW_BLUE="0;0;170";
    t_COLOR2="0;170;0";         t_LOW_GREEN="0;170;0";
    t_COLOR3="0;170;170";       t_LOW_CYAN="0;170;170";
    t_COLOR4="170;0;0";         t_LOW_RED="170;0;0";
    t_COLOR5="170;0;170";       t_LOW_MAGENTA="170;0;170";
    t_COLOR6="170;85;0";        t_BROWN="170;85;0";
    t_COLOR7="170;170;170";     t_LIGHT_GRAY="170;170;170";
    t_COLOR8="85;85;85";        t_DARK_GRAY="85;85;85";
    t_COLOR9="85;85;255";       t_HIGH_BLUE="85;85;255";
    t_COLOR10="85;255;85";      t_HIGH_GREEN="85;255;85";
    t_COLOR11="85;255;255";     t_HIGH_CYAN="85;255;255";
    t_COLOR12="255;85;85";      t_HIGH_RED="255;85;85";
    t_COLOR13="255;85;255";     t_HIGH_MAGENTA="255;85;255";
    t_COLOR14="255;255;85";     t_YELLOW="255;255;85";
    t_COLOR15="255;255;255";    t_WHITE="255;255;255";
fi
