#!/bin/sh
# generated by:
#  programmers-palettes
#  txt2fbterm.colors.sh
#  https://github.com/paulwratt/programmers-palettes/tree/master/bin

if echo "$TERM" | grep "fbterm" > /dev/null; then
    t_SETCOLOR='\033[3;%d;%s}';  # for printf
    # fbterm uses decimal values in tput/ESC codes for 256 colors
    # COLOR 0 is the transparencey (background image) color
    t_COLOR0="0;0;0";           t_VOID="0;0;0";
    t_COLOR1="157;157;157";     t_GREY="157;157;157";
    t_COLOR2="255;255;255";     t_WHITE="255;255;255";
    t_COLOR3="190;38;51";       t_RED="190;38;51";
    t_COLOR4="224;111;139";     t_MEAT="224;111;139";
    t_COLOR5="73;60;43";        t_DARK_BROWN="73;60;43";
    t_COLOR6="164;100;34";      t_BROWN="164;100;34";
    t_COLOR7="235;137;37";      t_ORANGE="235;137;37";
    t_COLOR8="247;226;107";     t_YELLOW="247;226;107";
    t_COLOR9="47;72;78";        t_DARK_GREEN="47;72;78";
    t_COLOR10="68;137;26";      t_GREEN="68;137;26";
    t_COLOR11="163;206;39";     t_SLIME_GREEN="163;206;39";
    t_COLOR12="27;38;50";       t_NIGHT_BLUE="27;38;50";
    t_COLOR13="0;87;137";       t_SEA_BLUE="0;87;137";
    t_COLOR14="49;162;242";     t_SKY_BLUE="49;162;242";
    t_COLOR15="178;220;239";    t_CLOUD_BLUE="178;220;239";
fi
