#!/bin/sh
# generated by:
#  programmers-palettes
#  txt2xterm.colors.sh
#  https://github.com/paulwratt/programmers-palettes/tree/master/bin

if echo "$TERM" | grep "xterm" > /dev/null; then
    # Arne16v20 16 color palette
    t_SETCOLOR='\033]4;%d;rgb:%s';  # for printf
    # xterm-color256: xterm screen rxvt urxtv gnome lxterminal tmux
    # xterm uses hexidecimal values in tput/ESC codes for 256 colors
    t_COLOR0="00/00/00";        t_VOID="00/00/00";
    t_COLOR1="9D/9D/9D";        t_GREY="9D/9D/9D";
    t_COLOR2="FF/FF/FF";        t_WHITE="FF/FF/FF";
    t_COLOR3="BE/26/33";        t_RED="BE/26/33";
    t_COLOR4="E0/6F/8B";        t_MEAT="E0/6F/8B";
    t_COLOR5="49/3C/2B";        t_DARK_BROWN="49/3C/2B";
    t_COLOR6="A4/64/22";        t_BROWN="A4/64/22";
    t_COLOR7="EB/89/25";        t_ORANGE="EB/89/25";
    t_COLOR8="F7/E2/6B";        t_YELLOW="F7/E2/6B";
    t_COLOR9="2F/48/4E";        t_DARK_GREEN="2F/48/4E";
    t_COLOR10="44/89/1A";       t_GREEN="44/89/1A";
    t_COLOR11="A3/CE/27";       t_SLIME_GREEN="A3/CE/27";
    t_COLOR12="1B/26/32";       t_NIGHT_BLUE="1B/26/32";
    t_COLOR13="00/57/89";       t_SEA_BLUE="00/57/89";
    t_COLOR14="31/A2/F2";       t_SKY_BLUE="31/A2/F2";
    t_COLOR15="B2/DC/EF";       t_CLOUD_BLUE="B2/DC/EF";
fi
