#!/bin/sh
# generated by:
#  programmers-palettes
#  txt2fbterm.colors.sh
#  https://github.com/paulwratt/programmers-palettes/tree/master/bin

if echo "$TERM" | grep "fbterm" > /dev/null; then
    t_SETCOLOR='\033[3;%d;%s}';  # for printf
    # fbterm uses decimal values in tput/ESC codes for 256 colors
    # COLOR 0 is the transparencey (background image) color
    t_COLOR0="78;74;78";        t_EMPEROR="78;74;78";
    t_COLOR1="68;36;52";        t_LIVID_BROWN="68;36;52";
    t_COLOR2="48;52;109";       t_RHINO="48;52;109";
    t_COLOR3="133;76;48";       t_MULE_FAWN="133;76;48";
    t_COLOR4="52;101;36";       t_WOODLAND="52;101;36";
    t_COLOR5="117;113;97";      t_PABLO="117;113;97";
    t_COLOR6="208;70;72";       t_FLUSH_MAHOGANY="208;70;72";
    t_COLOR7="89;125;206";      t_DANUBE="89;125;206";
    t_COLOR8="210;125;44";      t_BRANDY_PUNCH="210;125;44";
    t_COLOR9="109;170;44";      t_OLIVE_DRAB="109;170;44";
    t_COLOR10="133;149;161";    t_REGENT_GRAY="133;149;161";
    t_COLOR11="210;170;153";    t_EUNRY="210;170;153";
    t_COLOR12="109;194;202";    t_DOWNY="109;194;202";
    t_COLOR13="218;212;94";     t_TACHA="218;212;94";
    t_COLOR14="20;12;28";       t_EBONY="20;12;28";
    t_COLOR15="222;238;214";    t_ZANAH="222;238;214";
fi
