#!/bin/sh
# generated by:
#  programmers-palettes
#  txt2xterm.colors.sh
#  https://github.com/paulwratt/programmers-palettes/tree/master/bin

if echo "$TERM" | grep "xterm" > /dev/null; then
    # DawnBringer16 16 color palette
    t_SETCOLOR='\033]4;%d;rgb:%s';  # for printf
    # xterm-color256: xterm screen rxvt urxtv gnome lxterminal tmux
    # xterm uses hexidecimal values in tput/ESC codes for 256 colors
    t_COLOR0="4E/4A/4E";        t_EMPEROR="4E/4A/4E";
    t_COLOR1="44/24/34";        t_LIVID_BROWN="44/24/34";
    t_COLOR2="30/34/6D";        t_RHINO="30/34/6D";
    t_COLOR3="85/4C/30";        t_MULE_FAWN="85/4C/30";
    t_COLOR4="34/65/24";        t_WOODLAND="34/65/24";
    t_COLOR5="75/71/61";        t_PABLO="75/71/61";
    t_COLOR6="D0/46/48";        t_FLUSH_MAHOGANY="D0/46/48";
    t_COLOR7="59/7D/CE";        t_DANUBE="59/7D/CE";
    t_COLOR8="D2/7D/2C";        t_BRANDY_PUNCH="D2/7D/2C";
    t_COLOR9="6D/AA/2C";        t_OLIVE_DRAB="6D/AA/2C";
    t_COLOR10="85/95/A1";       t_REGENT_GRAY="85/95/A1";
    t_COLOR11="D2/AA/99";       t_EUNRY="D2/AA/99";
    t_COLOR12="6D/C2/CA";       t_DOWNY="6D/C2/CA";
    t_COLOR13="DA/D4/5E";       t_TACHA="DA/D4/5E";
    t_COLOR14="14/0C/1C";       t_EBONY="14/0C/1C";
    t_COLOR15="DE/EE/D6";       t_ZANAH="DE/EE/D6";
fi
